version: "3.8"

services:
  backend:
    build: ./backend
    ports: 
      - 5000:5000
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - ./volumes/db:/data/db
    restart: always
